#=========================================================================#
# doas.conf
#=========================================================================#

#=========================================================================#
# permit user
#=========================================================================#

permit keepenv setenv { PATH } djwilcox


#=========================================================================#
# allow root to switch to our user
#=========================================================================#

permit nopass keepenv setenv { PATH } root as djwilcox


#=========================================================================#
# permit user - no pass
#=========================================================================#

permit nopass keepenv setenv { PATH } djwilcox


#=========================================================================#
# root as root
#=========================================================================#

permit nopass keepenv root as root
