#=========================================================================#
# unbound custom.conf
#=========================================================================#

server:
	verbosity: 1
	access-control: 0.0.0.0/0 refuse
	access-control: 127.0.0.0/8 allow
	access-control: ::0/0 refuse
	access-control: ::1 allow
	access-control: ::ffff:127.0.0.1 allow
	
	# enable to not answer id.server and hostname.bind queries.
	hide-identity: yes
	hide-version: yes
	harden-glue: yes
	harden-dnssec-stripped: yes
        module-config: "validator iterator"

        # Ensure it's pointing to your updated anchor
        auto-trust-anchor-file: "/usr/local/etc/unbound/root.key"
        # dont query localhost needed for dnscrypt-proxy
        do-not-query-localhost: no
        # Reduce buffer size to avoid fragmentation issues on wifi
        edns-buffer-size: 1232
        do-ip4: yes
        do-ip6: no

include: "/usr/local/etc/unbound/forward.conf"
